chore(ci): fix generation
Signed-off-by: Evgeniy Frolov <evgeniy.frolov@flant.com>

diff --git a/.github/workflows/release_create-release.yml b/.github/workflows/release_create-release.yml
--- a/.github/workflows/release_create-release.yml
+++ b/.github/workflows/release_create-release.yml
@@ -14,7 +14,7 @@ on:
       pgp_key_urls:
         type: string
         required: true
-        description: 'PGP key URL(s) separated by space'
+        description: 'PGP key URL(s) separated by space (one per binary in same order)'
     secrets:
       TOKEN:
         required: true
@@ -42,9 +42,14 @@ jobs:
         id: notes
         run: |
           VERSION="${{ steps.get_version.outputs.version }}"
-          BINARY_NAMES="${{ inputs.binary_name }}"
+          BINARY_NAMES=(${{ inputs.binary_name }})
+          PGP_KEY_URLS=(${{ inputs.pgp_key_urls }})
           TUF_REPO="${{ inputs.tuf_repo }}"
-          PGP_KEY_URLS="${{ inputs.pgp_key_urls }}"
+          
+          if [ ${#BINARY_NAMES[@]} -ne ${#PGP_KEY_URLS[@]} ]; then
+            echo "Error: Number of binaries (${#BINARY_NAMES[@]}) doesn't match number of PGP keys (${#PGP_KEY_URLS[@]})"
+            exit 1
+          fi
           
           echo "## Changelog" > notes.md
           awk -v version="$VERSION" '
@@ -54,9 +59,10 @@ jobs:
           ' CHANGELOG.md >> notes.md
 
           echo -e "\n## Installation" >> notes.md
-          echo "To install the following binaries we strongly recommend following [these instructions](https://werf.io/getting_started/)." >> notes.md
-          
-          for BINARY_NAME in $BINARY_NAMES; do
+          for i in "${!BINARY_NAMES[@]}"; do
+            BINARY_NAME="${BINARY_NAMES[i]}"
+            PGP_URL="${PGP_KEY_URLS[i]}"
+            
             cat <<EOF >> notes.md
           You can download \`$BINARY_NAME\` binaries from here:
           * [Linux amd64](https://$TUF_REPO/targets/releases/$VERSION/linux-amd64/bin/$BINARY_NAME) ([PGP signature](https://$TUF_REPO/targets/signatures/$VERSION/linux-amd64/bin/$BINARY_NAME.sig))
@@ -64,12 +70,10 @@ jobs:
           * [macOS amd64](https://$TUF_REPO/targets/releases/$VERSION/darwin-amd64/bin/$BINARY_NAME) ([PGP signature](https://$TUF_REPO/targets/signatures/$VERSION/darwin-amd64/bin/$BINARY_NAME.sig))
           * [macOS arm64](https://$TUF_REPO/targets/releases/$VERSION/darwin-arm64/bin/$BINARY_NAME) ([PGP signature](https://$TUF_REPO/targets/signatures/$VERSION/darwin-arm64/bin/$BINARY_NAME.sig))
           * [Windows amd64](https://$TUF_REPO/targets/releases/$VERSION/windows-amd64/bin/$BINARY_NAME.exe) ([PGP signature](https://$TUF_REPO/targets/signatures/$VERSION/windows-amd64/bin/$BINARY_NAME.exe.sig))
-          EOF
-            echo -e "\nThese binaries were signed with PGP and could be verified on Linux with these commands:\n\`\`\`shell" >> notes.md
-            for PGP_URL in $PGP_KEY_URLS; do
-              echo "curl -sSL $PGP_URL | gpg --import" >> notes.md
-            done
-            cat <<EOF >> notes.md
+
+          These binaries were signed with PGP and could be verified on Linux with these commands:
+          \`\`\`shell
+          curl -sSL $PGP_URL | gpg --import
           curl -sSLO "https://$TUF_REPO/targets/releases/$VERSION/linux-amd64/bin/$BINARY_NAME"
           curl -sSLO "https://$TUF_REPO/targets/signatures/$VERSION/linux-amd64/bin/$BINARY_NAME.sig"
           gpg --verify $BINARY_NAME.sig $BINARY_NAME
